export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
export const FETCH_POST_COMMENTS_SUCESS = 'FETCH_POST_COMMENTS_SUCESS';
export const FETCH_POST_COMMENTS_ERROR = 'FETCH_POST_COMMENTS_ERROR';

export const START_POST_CREATION = 'START_POST_CREATION';
export const CHANGE_POST_TITLE_TEXT = 'CHANGE_POST_TITLE_TEXT';
export const CHANGE_POST_BODY_TEXT = 'CHANGE_POST_BODY_TEXT';
export const SAVE_POST = 'SAVE_POST';
